parameters:
#    emm_product.example.class: EMM\ProductBundle\Example

services:
#    emm_product.example:
#        class: %emm_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
